version: '3.8'

services:
  proxy:
    image: nginx:latest
    container_name: prod-proxy
    ports:
      - 80:80
    volumes:
      - ../deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    depends_on:
      - app

  app:
    build: 
      context: ..
      dockerfile: Dockerfile
    container_name: prod-server
    volumes:
      - ../src:/{{cookiecutter.project_name}}/src
    env_file:
      - ../.env/production/.app
    depends_on:
      - mysql
      - redis
    networks:
      - default
    command: >
      sh -c "./wait-for-it.sh redis:6379 --
             ./wait-for-it.sh mysql:3306 --
             python manage.py collectstatic --noinput
             gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000"

  mysql:
    image: mysql:8.0.20
    restart: always
    container_name: prod-mysql
    volumes:
      - mysql-volume:/var/lib/production/mysql
    env_file:
      - ../.env/production/.mysql
    command: |
      mysqld 
      --character-set-server=utf8 
      --collation-server=utf8_general_ci 
      --default-authentication-plugin=mysql_native_password
    networks:
      - default
  
  redis:
    image: redis:6.0-alpine
    container_name: prod-redis
    volumes:
      - redis-volume:/var/lib/production/redis/data
    networks:
      - default

volumes:
  mysql-volume:
  redis-volume:
