version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - /var/mysql_container_data:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=local
      - MYSQL_ROOT_PASSWORD=local_password123
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/{{cookiecutter.project_name}}/src
    environment:
      - MYSQL_DATABASE=local
      - MYSQL_USER=root
      - MYSQL_PASSWORD=local_password123
      - MYSQL_HOST=mysql
    ports:
      - "8000:8000"
    depends_on:
      - mysql
