version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/{{cookiecutter.project_name}}/src
    environment:
      - MYSQL_DATABASE=local
      - MYSQL_USER=root
      - MYSQL_PASSWORD=local_password123
      - MYSQL_HOST=mysql
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.20
    restart: always
    volumes:
      - /var/mysql_{{cookiecutter.project_name}}_data:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=local
      - MYSQL_ROOT_PASSWORD=local_password123
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
